[package]
name = "bevy_status_effects_macros"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[features]
bevy_butler = []

[dependencies]
proc-macro2 = "1.0"
proc-macro-error = "1.0"
quote = "1.0"
syn = { version = "2.0", features = ["full"] }
